// <auto-generated />
using System;
using ContractManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractManagement.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617135129_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContractManagement.API.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Business Avenue, New York, NY 10001",
                            CreatedAt = new DateTime(2026, 6, 17, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2593),
                            Email = "contact@abccorp.com",
                            Name = "ABC Corporation",
                            Phone = "+1 (555) 123-4567",
                            Region = "North America"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Commerce Street, London, UK",
                            CreatedAt = new DateTime(2026, 6, 17, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2597),
                            Email = "info@xyzent.com",
                            Name = "XYZ Enterprises",
                            Phone = "+44 20 1234 5678",
                            Region = "Europe"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Innovation Drive, Sydney, Australia",
                            CreatedAt = new DateTime(2026, 6, 17, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2600),
                            Email = "sales@techsolutions.com",
                            Name = "Tech Solutions Ltd",
                            Phone = "+61 2 9876 5432",
                            Region = "Asia Pacific"
                        });
                });

            modelBuilder.Entity("ContractManagement.API.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceLevel")
                        .HasColumnType("int");

                    b.Property<string>("SignedAgreementFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedAgreementPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Status");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 6, 17, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2656),
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceLevel = 2,
                            SignedAgreementFileName = "ABC_Corp_Contract_2024.pdf",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreatedAt = new DateTime(2026, 6, 17, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2661),
                            EndDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceLevel = 0,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 6, 17, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2664),
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceLevel = 1,
                            StartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 3,
                            CreatedAt = new DateTime(2026, 6, 17, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2666),
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceLevel = 3,
                            SignedAgreementFileName = "TechSolutions_Enterprise_2024.pdf",
                            StartDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        });
                });

            modelBuilder.Entity("ContractManagement.API.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ServiceRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAt = new DateTime(2026, 6, 12, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2947),
                            ContractId = 1,
                            Cost = 5000m,
                            CreatedAt = new DateTime(2026, 5, 18, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2935),
                            Description = "System integration support for ERP migration",
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            ContractId = 1,
                            Cost = 3500m,
                            CreatedAt = new DateTime(2026, 6, 2, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2955),
                            Description = "Security audit and penetration testing",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            ContractId = 1,
                            Cost = 2500m,
                            CreatedAt = new DateTime(2026, 6, 12, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2957),
                            Description = "24/7 monitoring setup",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            ContractId = 4,
                            Cost = 15000m,
                            CreatedAt = new DateTime(2026, 6, 7, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2960),
                            Description = "Cloud migration assistance (AWS to Azure)",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            ContractId = 4,
                            Cost = 8000m,
                            CreatedAt = new DateTime(2026, 6, 10, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(2962),
                            Description = "DevOps pipeline implementation",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ContractManagement.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 17, 13, 51, 27, 944, DateTimeKind.Utc).AddTicks(8466),
                            PasswordHash = "$2a$11$fSFIKzhboNYQNpvCLvCaEuPKQZGak23OSr0Z4sblvdKVE/MXfiOMu",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 17, 13, 51, 28, 120, DateTimeKind.Utc).AddTicks(1402),
                            PasswordHash = "$2a$11$EWyd7acwzVzlKiypgTJVH.hj.wVg.YEc.jgmQnmc9fhgf0nc4pE62",
                            Role = "Manager",
                            Username = "manager"
                        });
                });

            modelBuilder.Entity("ContractManagement.API.Models.Contract", b =>
                {
                    b.HasOne("ContractManagement.API.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ContractManagement.API.Models.ServiceRequest", b =>
                {
                    b.HasOne("ContractManagement.API.Models.Contract", "Contract")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("ContractManagement.API.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("ContractManagement.API.Models.Contract", b =>
                {
                    b.Navigation("ServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
